### ISSUE TITLE
部分执行文件运行会报错

### ISSUE THREAD

**Issue by GuoYJ1719** [PuYuuu/CppRobotics#1]
好像是有关draw_vehicle的部分：
./hybrid_astar: symbol lookup error: ./hybrid_astar: undefined symbol: _ZN5utils12draw_vehicleEN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEEdNS_13VehicleConfigENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbb

**Comment by PuYuuu** [comment]
报错截图贴出来一下看下呢？可以检查下matplotlib和numpy的版本，我本地是matplotlib 3.7.4，numpy 1.24.4
